### ISSUE TITLE
Generic solution

### ISSUE THREAD

**Issue by vasilich6107** [agent3bood/Flutter-architecture-app#2]
You can try this library with generic approach for cooking graphql_flutter + bloc 
https://pub.dev/packages/graphql_flutter_bloc

**Comment by agent3bood** [comment]
The suggested library is not generic, in face it assume using `graphql_flutter`, this repo is an example of how to use graphql with Bloc.

**Comment by vasilich6107** [comment]
According to the pubspec this repo also uses “ graphql_flutter”)

**Comment by agent3bood** [comment]
`graphql_flutter` is used in the repository only and can be swapped for any other library.
